class_name SfxLayers
## GENERATED by tools/audio/sfx_layer.py: do not edit. The shipped takes per SfxSystem sound, built from
## ElevenLabs source material layered with the synthesised transients (assets/audio/elevenlabs/sources.json).
## A sound listed here plays these takes instead of its synthesised ones.

const TAKES := {
	"autocannon_shot": ["res://assets/audio/layered/autocannon_shot_1.ogg", "res://assets/audio/layered/autocannon_shot_2.ogg", "res://assets/audio/layered/autocannon_shot_3.ogg"],
	"mg_loop": ["res://assets/audio/layered/mg_loop_1.wav"],
	"shell_hit_armor": ["res://assets/audio/layered/shell_hit_armor_1.ogg", "res://assets/audio/layered/shell_hit_armor_2.ogg", "res://assets/audio/layered/shell_hit_armor_3.ogg"],
	"tank_boom": ["res://assets/audio/layered/tank_boom_1.ogg", "res://assets/audio/layered/tank_boom_2.ogg", "res://assets/audio/layered/tank_boom_3.ogg"],
}
