class_name SfxDirections
## GENERATED by tools/audio/gun_layers.py from assets/audio/gun_designs.json: do not edit. Round 17 (G3):
## each sound's DIRECTIONS - the same sound designed more than one way, in layers, as stereo takes - for
## the lead's ear on the audition page. SfxSystem.DIRECTION picks the one the game plays.

const TAKES := {
	"tank_boom": {"a": ["res://assets/audio/layered/tank_boom~a_1.wav", "res://assets/audio/layered/tank_boom~a_2.wav", "res://assets/audio/layered/tank_boom~a_3.wav", "res://assets/audio/layered/tank_boom~a_4.wav"], "b": ["res://assets/audio/layered/tank_boom~b_1.wav", "res://assets/audio/layered/tank_boom~b_2.wav", "res://assets/audio/layered/tank_boom~b_3.wav"], "c": ["res://assets/audio/layered/tank_boom~c_1.wav", "res://assets/audio/layered/tank_boom~c_2.wav", "res://assets/audio/layered/tank_boom~c_3.wav"]},
}

## sound -> direction -> what it is, in a line (the page shows it).
const LABELS := {
	"tank_boom": {"a": "120 mm at 50 m: N-wave crack, generated report, 38 Hz sub, breech, stereo rolling tail", "b": "across the valley: the crack arrives first, the boom after, echoes rolling off the hills", "c": "today's boom with what it lacks added: the crack, a sub and the stereo tail (the source fix alone)"},
}
